### ISSUE TITLE
Back end specific project add/remove

### ISSUE THREAD

**Issue by kwehden** [ibm-quantum/Hub-Automation#5]
API endpoint to add/remove a backend asset to/from a specific project

**Comment by Matt-Stypulkoski** [comment]
For adding a backend from a specific project:
`POST    /Network/{hubName}/Groups/{groupName}/Projects/{projectName}/devices`
Data required:
`{"name": "<backend_name>", "priority": <int between 1-10000>}`

For deleting a backend from a specific project:
`DELETE    /Network/{hubName}/Groups/{groupName}/Projects/{projectName}/devices/{deviceName}`
